// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps.js';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"components/aa/index":{"id":"components/aa/index","path":"components/aa","parentId":"DocLayout"},"components/bb/index":{"id":"components/bb/index","path":"components/bb","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__.pnpm__dumi_2.1.14_lfoodr2hdmy7hzfgwjnbclkduy__node_modules__dumi__dist__client__pages__404" */'/Users/baijiashuo/tanka/mono-pnpm-changesets/node_modules/.pnpm/dumi@2.1.14_lfoodr2hdmy7hzfgwjnbclkduy/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/baijiashuo/tanka/mono-pnpm-changesets/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__.pnpm__dumi_2.1.14_lfoodr2hdmy7hzfgwjnbclkduy__node_modules__dumi__theme-default__layouts__DocLayout__index" */'/Users/baijiashuo/tanka/mono-pnpm-changesets/node_modules/.pnpm/dumi@2.1.14_lfoodr2hdmy7hzfgwjnbclkduy/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'components/aa/index': React.lazy(() => import(/* webpackChunkName: "packages__aa__index.md" */'/Users/baijiashuo/tanka/mono-pnpm-changesets/packages/aa/index.md')),
'components/bb/index': React.lazy(() => import(/* webpackChunkName: "packages__bb__index.md" */'/Users/baijiashuo/tanka/mono-pnpm-changesets/packages/bb/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__.pnpm__dumi_2.1.14_lfoodr2hdmy7hzfgwjnbclkduy__node_modules__dumi__dist__client__pages__Demo__index" */'/Users/baijiashuo/tanka/mono-pnpm-changesets/node_modules/.pnpm/dumi@2.1.14_lfoodr2hdmy7hzfgwjnbclkduy/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
