// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/baijiashuo/tanka/mono-pnpm-changesets/node_modules/.pnpm/dumi@2.1.14_lfoodr2hdmy7hzfgwjnbclkduy/node_modules/dumi/theme-default/slots/Toc/index.js';
